export const tdrexAssetsData: any[] = [
  {
    chainId: 1,
    decimals: 18,
    symbol: 'TP26',
    name: 'Prefixed Treasury 2026',
    isNative: true,
    isToken: true,
    address: 'a',
    wrapped: {
      chainId: 1,
      decimals: 18,
      symbol: 'TP26',
      name: 'Prefixed Treasury 2026',
      isNative: false,
      isToken: true,
      address: 'a',
    },
  },
  {
    chainId: 2,
    decimals: 18,
    symbol: 'TP29',
    name: 'Prefixed Treasury 2029',
    isNative: false,
    isToken: true,
    address: 'b',
    wrapped: {
      chainId: 2,
      decimals: 18,
      symbol: 'TP29',
      name: 'Prefixed Treasury 2029',
      isNative: false,
      isToken: true,
      address: 'b',
    },
  },
  {
    chainId: 3,
    decimals: 18,
    symbol: 'TS26',
    name: 'Treasury Selic 2026',
    isNative: false,
    isToken: true,
    address: 'c',
    wrapped: {
      chainId: 3,
      decimals: 18,
      symbol: 'TS26',
      name: 'Treasury Selic 2026',
      isNative: false,
      isToken: true,
      address: 'c',
    },
  },
  {
    chainId: 4,
    decimals: 18,
    symbol: 'TS29',
    name: 'Treasury Selic 2029',
    isNative: false,
    isToken: true,
    address: 'd',
    wrapped: {
      chainId: 4,
      decimals: 18,
      symbol: 'TS29',
      name: 'Treasury Selic 2029',
      isNative: false,
      isToken: true,
      address: 'd',
    },
  },
]

/**
 * CBDCs: Colombia, DREX, Hong Kong, Japan, Uruguai
 *
 */
export const tdrexCBDCsData: any[] = [
  {
    chainId: 1,
    decimals: 18,
    symbol: 'COL',
    name: 'Colombia',
    isNative: true,
    isToken: true,
    address: 'e',
    wrapped: {
      chainId: 1,
      decimals: 18,
      symbol: 'COL',
      name: 'Colombia',
      isNative: false,
      isToken: true,
      address: 'e',
    },
  },
  {
    chainId: 2,
    decimals: 18,
    symbol: 'DREX',
    name: 'DREX',
    isNative: false,
    isToken: true,
    address: 'f',
    wrapped: {
      chainId: 2,
      decimals: 18,
      symbol: 'DREX',
      name: 'DREX',
      isNative: false,
      isToken: true,
      address: 'f',
    },
  },
  {
    chainId: 3,
    decimals: 18,
    symbol: 'HKG',
    name: 'Hong Kong',
    isNative: false,
    isToken: true,
    address: 'g',
    wrapped: {
      chainId: 3,
      decimals: 18,
      symbol: 'HKG',
      name: 'Hong Kong',
      isNative: false,
      isToken: true,
      address: 'g',
    },
  },
  {
    chainId: 4,
    decimals: 18,
    symbol: 'JPY',
    name: 'Japan',
    isNative: false,
    isToken: true,
    address: 'h',
    wrapped: {
      chainId: 4,
      decimals: 18,
      symbol: 'JPY',
      name: 'Japan',
      isNative: false,
      isToken: true,
      address: 'h',
    },
  },
  {
    chainId: 5,
    decimals: 18,
    symbol: 'URY',
    name: 'Uruguay',
    isNative: false,
    isToken: true,
    address: 'i',
    wrapped: {
      chainId: 5,
      decimals: 18,
      symbol: 'URY',
      name: 'Uruguay',
      isNative: false,
      isToken: true,
      address: 'i',
    },
  },
]
