/* eslint-disable import/no-unused-modules */
export const mocked_participants = [
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'ZEL',
    name: 'New Zeland',
    profile: 'Administrator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'NZD',
    countryImg: 'https://i.im.ge/2023/12/12/E6bTaF.new-zeland.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/12/E6bTaF.new-zeland.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    id: 'VG9rZW46RVRIRVJFVU1fMHgyMjYwZmFjNWU1NTQyYTc3M2FhNDRmYmNmZWRmN2MxOTNiYzJjNTk5',
    name: 'Santander',
    chain: 'ETHEREUM',
    profile: 'Seller',
    countryImg: 'https://i.im.ge/2023/12/04/C4zQBT.image-76.png',
    address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    symbol: 'STD',
    standard: 'ERC20',
    localCurrency: 'EUR',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHgyMjYwRkFDNUU1NTQyYTc3M0FhNDRmQkNmZURmN0MxOTNiYzJDNTk5X1VTRA==',
      totalValueLocked: {
        id: 'QW1vdW50OjE3NDY2Mjg2MC41MjI3NjUzN19VU0Q=',
        value: 1.7466286052276537e8,
        currency: 'USD',
        __typename: 'Amount',
      },
      price: {
        id: 'QW1vdW50OjM3MjgwLjgxNjgzNDI1ODg0X1VTRA==',
        value: 2877.98,
        currency: 'USD',
        __typename: 'Amount',
      },
      pricePercentChange: {
        id: 'QW1vdW50Oi0xLjE1NDE4MzAxMTkyODgyN19VU0Q=',
        currency: 'USD',
        value: -1.154183011928827,
        __typename: 'Amount',
      },
      volume: {
        id: 'QW1vdW50OjE5NzQ4NjY3LjI1Mjg5OTE3X1VTRA==',
        value: 1.974866725289917e7,
        currency: 'USD',
        __typename: 'Amount',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4MjI2MGZhYzVlNTU0MmE3NzNhYTQ0ZmJjZmVkZjdjMTkzYmMyYzU5OV9XcmFwcGVkIEJpdGNvaW4=',
      logoUrl: 'https://i.im.ge/2023/12/12/ENgq6L.santander.png',
      __typename: 'TokenProject',
      description:
        "This title expires on 03/01/2029. Recommended for those who want to make medium-term investments Title with daily profitability linked to the economy's interest rate (Selic rate). This means that if the Selic rate increases, your profitability increases and if the Selic rate decreases, your profitability decreases. As it does not pay half-yearly interest, it is more interesting for those who can let their money earn until the investment matures.",
    },
    __typename: 'Token',
  },
  {
    id: 'VG9rZW46RVRIRVJFVU1fMHgyMjYwZmFjNWU1NTQyYTc3M2FhNDRmYmNmZWRmN2MxOTNiYzJjNTk5',
    name: 'Montenegro',
    chain: 'ETHEREUM',
    profile: 'Administrator',
    countryImg: 'https://i.im.ge/2023/12/12/E6yauW.montenegro-flag-png-large.jpg',
    address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    symbol: 'MTN',
    standard: 'ERC20',
    localCurrency: 'EUR',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHgyMjYwRkFDNUU1NTQyYTc3M0FhNDRmQkNmZURmN0MxOTNiYzJDNTk5X1VTRA==',
      totalValueLocked: {
        id: 'QW1vdW50OjE3NDY2Mjg2MC41MjI3NjUzN19VU0Q=',
        value: 1.7466286052276537e8,
        currency: 'USD',
        __typename: 'Amount',
      },
      price: {
        id: 'QW1vdW50OjM3MjgwLjgxNjgzNDI1ODg0X1VTRA==',
        value: 2877.98,
        currency: 'USD',
        __typename: 'Amount',
      },
      pricePercentChange: {
        id: 'QW1vdW50Oi0xLjE1NDE4MzAxMTkyODgyN19VU0Q=',
        currency: 'USD',
        value: -1.154183011928827,
        __typename: 'Amount',
      },
      volume: {
        id: 'QW1vdW50OjE5NzQ4NjY3LjI1Mjg5OTE3X1VTRA==',
        value: 1.974866725289917e7,
        currency: 'USD',
        __typename: 'Amount',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4MjI2MGZhYzVlNTU0MmE3NzNhYTQ0ZmJjZmVkZjdjMTkzYmMyYzU5OV9XcmFwcGVkIEJpdGNvaW4=',
      logoUrl: 'https://i.im.ge/2023/12/12/E6yauW.montenegro-flag-png-large.jpg',
      __typename: 'TokenProject',
      description:
        "This title expires on 03/01/2029. Recommended for those who want to make medium-term investments Title with daily profitability linked to the economy's interest rate (Selic rate). This means that if the Selic rate increases, your profitability increases and if the Selic rate decreases, your profitability decreases. As it does not pay half-yearly interest, it is more interesting for those who can let their money earn until the investment matures.",
    },
    __typename: 'Token',
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'URY',
    name: 'Uruguay',
    profile: 'Administrator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'UYU',
    countryImg: 'https://i.im.ge/2023/12/04/C4zMY0.image-79-1.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/04/C4zMY0.image-79-1.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'HOK',
    name: 'Hong Kong',
    profile: 'Administrator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'HKD',
    countryImg: 'https://i.im.ge/2023/12/04/C4zosc.image-69.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/04/C4zosc.image-69.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'JAP',
    name: 'Japan',
    profile: 'Administrator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'YEN ¥',
    countryImg: 'https://i.im.ge/2023/12/04/C4zlzG.image-74.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/04/C4zlzG.image-74.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'UAE',
    name: 'United Arab Emirates',
    profile: 'Administrator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'AED',
    countryImg: 'https://i.im.ge/2023/12/12/E6boyK.UAE.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/12/E6boyK.UAE.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'ITAU',
    name: 'ITAU',
    profile: 'Buyer',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'UYU',
    countryImg: 'https://i.im.ge/2023/12/04/C4zMY0.image-79-1.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/12/ENg7lx.itau.jpg',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg4MzkwYTFkYTA3ZTM3NmVmN2FkZDRiZTg1OWJhNzRmYjgzYWEwMmQ1',
    name: 'Republic of Palau',
    profile: 'Administrator',
    countryImg: 'https://i.im.ge/2023/12/12/E6w0hX.palau.png',
    standard: 'ERC20',
    symbol: 'PALAU',
    chain: 'ETHEREUM',
    address: '0x8390a1da07e376ef7add4be859ba74fb83aa02d5',
    localCurrency: 'USD',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg4MzkwYTFEQTA3RTM3NmVmN2FEZDRCZTg1OUJBNzRGYjgzYUEwMkQ1X1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjAuMDE3Mzk4MjkwODU3OTY4MzM2X1VTRA==',
        value: 166.1,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50OjQxLjE0OTY0MjkxOTUzMDg3Nl9VU0Q=',
        currency: 'USD',
        value: 41.149642919530876,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjQwMzg3MDIuNjkxNDM1NTM4X1VTRA==',
        value: 4038702.691435538,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE5NDQ3OTA3LjE1ODg0NjJfVVNE',
        value: 19447907.1588462,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4ODM5MGExZGEwN2UzNzZlZjdhZGQ0YmU4NTliYTc0ZmI4M2FhMDJkNV9Hcm9r',
      logoUrl: 'https://i.im.ge/2023/12/12/E6w0hX.palau.png',
      __typename: 'TokenProject',
      description:
        'The "Prefixed Treasury 2026" is an investment with maturity on 01/01/2026, yielding R$1,000 per security at maturity. It is ideal for medium-term investments without semi-annual interest, and can be redeemed in advance at market value.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'AHSBC',
    name: 'AHSBC',
    profile: 'Liquidity generator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'UYU',
    countryImg: 'https://i.im.ge/2023/12/04/C4zMY0.image-79-1.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/12/ENgsKG.hsbc.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
  {
    __typename: 'Token',
    id: 'VG9rZW46RVRIRVJFVU1fMHg1MTQ5MTA3NzFhZjljYTY1NmFmODQwZGZmODNlODI2NGVjZjk4NmNh',
    standard: 'ERC20',
    symbol: 'JPM',
    name: 'JP Morgan',
    profile: 'Pool Creator',
    slug: 'tesouro-prefixado-2029',
    localCurrency: 'UYU',
    countryImg: 'https://i.im.ge/2023/12/04/C4zMY0.image-79-1.png',
    address: '0x514910771af9ca656af840dff83e8264ecf986ca',
    chain: 'ETHEREUM',
    market: {
      id: 'VG9rZW5NYXJrZXQ6RVRIRVJFVU1fMHg1MTQ5MTA3NzFBRjlDYTY1NmFmODQwZGZmODNFODI2NEVjRjk4NkNBX1VTRA==',
      price: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE0LjY2NzE3Njg1Njk2OTI5Ml9VU0Q=',
        value: 120.78,
        currency: 'USD',
      },
      pricePercentChange: {
        __typename: 'Amount',
        id: 'QW1vdW50Oi0wLjgyOTgwMjYzMzU5Mjg5NjdfVVNE',
        currency: 'USD',
        value: -0.8298026335928967,
      },
      totalValueLocked: {
        __typename: 'Amount',
        id: 'QW1vdW50OjI5NjU5MjI1Ljc0MTIyOTcxN19VU0Q=',
        value: 29659225.741229717,
        currency: 'USD',
      },
      volume: {
        __typename: 'Amount',
        id: 'QW1vdW50OjE2MzUzMzE3LjA0MzEwMTMxX1VTRA==',
        value: 16353317.04310131,
        currency: 'USD',
      },
      __typename: 'TokenMarket',
    },
    project: {
      id: 'VG9rZW5Qcm9qZWN0OkVUSEVSRVVNXzB4NTE0OTEwNzcxYWY5Y2E2NTZhZjg0MGRmZjgzZTgyNjRlY2Y5ODZjYV9DaGFpbmxpbms',
      logoUrl: 'https://i.im.ge/2023/12/12/ENZWOT.Chase-Emblem.png',
      __typename: 'TokenProject',
      standard: 'ERC20',
      symbol: 'ETH',
      description:
        'This title expires on 01/01/2029. Recommended for those who want to make medium-term investments. Prefixed title, that is, at the time of purchase, you already know exactly how much you will receive in the future (always R$1,000 per unit of title). It is more interesting for those who can let their money earn until the investment matures, as it does not pay half-yearly interest. In case of early redemption, the National Treasury guarantees its repurchase at market values.',
    },
  },
]
